version: "3.8"

services:
  app:
    container_name: app-springboot-reacitve
    image: app-springboot-reacitve
    build: ./
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
    - "27017:27017"

